# SOD IDE build config
# Launches BC++ IDE, auto-builds project.

[render]
windowresolution = 1280x960
output = texture_nn
aspect = true

[cpu]
cputype  = 386_vm
cycles   = max

[mixer]
rate     = 44100

[autoexec]
mount C ~/dosbox # Directory for BC++ IDE
mount D ~/Documents/git/wolf3d-plus/WOLFSRC # Source code directory
set PATH=C:\BC31\BIN
C:
cd \bc31\bin
bc /b D:\SOD.PRJ > D:\OBJ\SOD.LOG
type D:\OBJ\SOD.LOG
#exit
