# Wolf3D game test config

[sdl]
windowresolution = large
output = openglnb


[render]
aspect = true
scaler = none
integer_scaling = auto
glshader = crt-aperture

[dosbox]
machine = svga_s3

[cpu]
cputype = auto
cycles = 20000

[mixer]
rate = 48000
reverb = medium
chorus = normal

[speaker]
disabled = false

[autoexec]
mount C ~/dosbox # Directory for BC++ IDE
mount D ~/Documents/git/wolf3d-plus/WOLFSRC # Source code directory
C:
cls
copy D:\OBJ\WOLF3D.EXE C:\GAMES\WOLF3D\
cd GAMES\WOLF3D
WOLF3D.EXE
exit