# SOD game test config

[render]
windowresolution = 1280x960
output = texture_nn
aspect = true

[cpu]
cputype  = 386_vm
cycles   = max

[mixer]
rate     = 44100

[speaker]
disabled = false

[autoexec]
mount C ~/dosbox # Directory for BC++ IDE
mount D ~/Documents/git/wolf3d-plus/WOLFSRC # Source code directory
C:
cls
copy D:\OBJ\SOD.EXE C:\GAMES\SOD\
cd GAMES\SOD
SOD.EXE
exit